name: Publish Website

on:
  push:
    branches:
      - main

jobs:
  build-deploy:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v2
    - name: Set Node.js 16
      uses: actions/setup-node@v2.4.1
      with:
        node-version: 18.x  # Use a newer version like 16.x or 18.x
    - name: Cache node_modules
      uses: actions/cache@v2
      with:
        path: node_modules
        key: ${{ runner.os }}-node-${{ hashFiles('**/package-lock.json') }}
        restore-keys: |
          ${{ runner.os }}-node-
    - name: Install dependencies
      run: npm install
    - name: Test
      run: npm run test --if-present
    - name: Build
      run: npm run build --if-present
    - name: Deploy
      uses: peaceiris/actions-gh-pages@v4
      with:
        github_token: ${{ secrets.GITHUB_TOKEN }}
        publish_dir: ./dist

  build-deploynoRoot:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v2
    - name: Set Node.js 14
      uses: actions/setup-node@v2.4.1
      with:
        node-version: 18.x
    - name: Cache node_modules
      uses: actions/cache@v2
      with:
        path: node_modules
        key: ${{ runner.os }}-node-${{ hashFiles('**/package-lock.json') }}
        restore-keys: |
          ${{ runner.os }}-node-
    - name: Install dependencies
      run: npm install
    - name: Test
      run: npm run test --if-present
    - name: Build
      run: npm run buildNotRoot --if-present
    - name: Deploy
      uses: s0/git-publish-subdir-action@develop
      env:
        REPO: self
        BRANCH: ready-noRoot
        FOLDER: dist
        GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}